=== jose-navarro/workflowmaker/data/toolkit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by XMLSPY 2004 Professional Ed. Release 2, Installed Multi for 10 users (SOFTWARE AG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="toolkit">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:token"/>
				<xs:element name="description" type="xs:token"/>
				<xs:element name="parameters">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="parameter" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:token"/>
										<xs:element name="description" type="xs:token"/>
										<xs:element name="type">
											<xs:simpleType>
												<xs:restriction base="xs:token">
													<xs:enumeration value="integer"/>
													<xs:enumeration value="real"/>
													<xs:enumeration value="boolean"/>
													<xs:enumeration value="string"/>
													<xs:enumeration value="INTEGER"/>
													<xs:enumeration value="REAL"/>
													<xs:enumeration value="BOOLEAN"/>
													<xs:enumeration value="STRING"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="file_types">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="file_type" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:token"/>
										<xs:element name="description" type="xs:token"/>
										<xs:element name="extension" type="xs:token"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="tasks">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="task" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:token"/>
										<xs:element name="description" type="xs:token"/>
										<xs:element name="name_of_executable" type="xs:token"/>
										<xs:element name="parameters" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="parameter_id" type="xs:token" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="input_files" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="input_file" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="file_type_id" type="xs:token"/>
																<xs:element name="description" type="xs:token"/>
																<xs:element name="options_file_label" type="xs:token"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="output_files">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="output_file" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="file_type_id" type="xs:token"/>
																<xs:element name="description" type="xs:token"/>
																<xs:element name="options_file_label" type="xs:token"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jose-navarro/workflowmaker/installer/installer_sw_windows/deployment/data_samples/image_processing_toolkit.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<toolkit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="toolkit.xsd">
  <id>IMAGE_PROCESSING_TOOLKIT</id>
  <description>Sample toolkit with a few image processing tools</description>
  <parameters>
    <parameter>
      <id>RADIUS</id>
      <description>Radius (in pixels) for which an image processing function is applied</description>
      <type>REAL</type>
    </parameter>
    <parameter>
      <id>SIGMA</id>
      <description>Standard deviation for the image processing function applied</description>
      <type>REAL</type>
    </parameter>
    <parameter>
      <id>DEGREES</id>
      <description>Amount in degrees to apply by the image processing function</description>
      <type>REAL</type>
    </parameter>
    <parameter>
      <id>FLIP_MODE</id>
      <description>Flip the image horizontally (0) or vertically (1)?</description>
      <type>INTEGER</type>
    </parameter>
  </parameters>
  <file_types>
    <file_type>
      <id>IMAGE_JPG</id>
      <description>An image in JPG format</description>
      <extension>jpg</extension>
    </file_type>
    <file_type>
      <id>IMAGE_PNG</id>
      <description>An image in PGN format</description>
      <extension>png</extension>
    </file_type>
  </file_types>
  <tasks>
    <task>
      <id>MOSAIC</id>
      <description>Mosaics two JPG images</description>
      <name_of_executable>mosaic</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Image that will be copied to the LEFT part of the mosaic</description>
          <options_file_label>LEFT_IMAGE_FILENAME</options_file_label>
        </input_file>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Image that will be copied to the RIGHT side of the mosaic</description>
          <options_file_label>RIGHT_IMAGE_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>The output mosaic</description>
          <options_file_label>MOSAIC_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>BLUR</id>
      <description>Blur an image</description>
      <name_of_executable>blur</name_of_executable>
      <parameters>
        <parameter_id>RADIUS</parameter_id>
        <parameter_id>SIGMA</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>JPEG image to blur</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Output, blurred JPG image</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>CHARCOAL</id>
      <description>Apply the charcoal effect to an image</description>
      <name_of_executable>charcoal</name_of_executable>
      <parameters>
        <parameter_id>RADIUS</parameter_id>
        <parameter_id>SIGMA</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Input JPG file to which the charcoal effect will be applied</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Output JPG image, with the charcoal effect applied</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>OILPAINT</id>
      <description>Apply the oil paint effect to an image</description>
      <name_of_executable>oilpaint</name_of_executable>
      <parameters>
        <parameter_id>RADIUS</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>The input JPG file to which the oil paint effect will be applied</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>The output JPG file, with the oil paint effect applied</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>ROTATE</id>
      <description>Rotate an image</description>
      <name_of_executable>rotate</name_of_executable>
      <parameters>
        <parameter_id>DEGREES</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Image to rotate</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Image rotated</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>MIRROR</id>
      <description>Mirrors an image, either horizontally or vertically</description>
      <name_of_executable>mirror</name_of_executable>
      <parameters>
        <parameter_id>FLIP_MODE</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Image to be mirrored</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Mirrored image</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>GRAYSCALE</id>
      <description>Converts a color image to grayscale</description>
      <name_of_executable>grayscale</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Color image to convert to grayscale</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Output grayscale image</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>JPG2PNG</id>
      <description>Convert a JPG image to PNG format</description>
      <name_of_executable>jpg2png</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>JPG image to convert</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_PNG</file_type_id>
          <description>Converted PNG image</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>PNG2JPG</id>
      <description>Convert a PNG image to JPG format</description>
      <name_of_executable>png2jpg</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>IMAGE_PNG</file_type_id>
          <description>PNG image to convert</description>
          <options_file_label>INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>IMAGE_JPG</file_type_id>
          <description>Converted JPG image</description>
          <options_file_label>OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
  </tasks>
</toolkit>

=== jose-navarro/workflowmaker/samples/text_file_processing/sample_workflowmaker_files/text_file_processing_toolkit.xml
<?xml version="1.0" encoding="ISO-8859-1"?>

<toolkit xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="toolkit.xsd">
  <id>TEXT_FILE_PROCESSING_TOOLKIT</id>
  <description>Simple set of text file utilities</description>
  <parameters>
    <parameter>
      <id>CUT_TAIL_MAX_LINES</id>
      <description>Maximum number of lines to keep when removing the queue of some text file</description>
      <type>INTEGER</type>
    </parameter>
    <parameter>
      <id>INTERLEAVE_COPY_QUEUE</id>
      <description>Copy (not zero) or not (0) the remaining lines in the longest file when interleaving two text files </description>
      <type>INTEGER</type>
    </parameter>
  </parameters>
  <file_types>
    <file_type>
      <id>TXT</id>
      <description>Text file</description>
      <extension>txt</extension>
    </file_type>
  </file_types>
  <tasks>
    <task>
      <id>APPEND</id>
      <description>Appends two files</description>
      <name_of_executable>append</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>First file to append</description>
          <options_file_label>APPEND_INPUT_FILENAME_1</options_file_label>
        </input_file>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>Second file to append</description>
          <options_file_label>APPEND_INPUT_FILENAME_2</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>TXT</file_type_id>
          <description>Result of appending the two input files</description>
          <options_file_label>APPEND_OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>CUT_TAIL</id>
      <description>Remove the last lines of some file, keeping only some at the beginning</description>
      <name_of_executable>cut_tail</name_of_executable>
      <parameters>
        <parameter_id>CUT_TAIL_MAX_LINES</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>Fille whose last lines must be removed</description>
          <options_file_label>CUT_TAIL_INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>TXT</file_type_id>
          <description>File whose last lines have been removed</description>
          <options_file_label>CUT_TAIL_OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>INTERLEAVE</id>
      <description>Interleave the lines of two files, copying or not the queue of the longest one</description>
      <name_of_executable>interleave</name_of_executable>
      <parameters>
        <parameter_id>INTERLEAVE_COPY_QUEUE</parameter_id>
      </parameters>
      <input_files>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>First file whose lines must be interleaved</description>
          <options_file_label>INTERLEAVE_INPUT_FILENAME_1</options_file_label>
        </input_file>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>Second file whose lines must be interleaved</description>
          <options_file_label>INTERLEAVE_INPUT_FILENAME_2</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>TXT</file_type_id>
          <description>File with lines interleaved and, optionally, the remaining lines of the longest file</description>
          <options_file_label>INTERLEAVE_OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>REVERSE</id>
      <description>Reverse (right to left) the lines in a text file</description>
      <name_of_executable>reverse</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>File whose lines must be reversed</description>
          <options_file_label>REVERSE_INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>TXT</file_type_id>
          <description>File whose lines have been reversed</description>
          <options_file_label>REVERSE_OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
    <task>
      <id>TO_UPPERCASE</id>
      <description>Capitalize all letters in a text file</description>
      <name_of_executable>to_uppercase</name_of_executable>
      <input_files>
        <input_file>
          <file_type_id>TXT</file_type_id>
          <description>File whose letters must be capitalized</description>
          <options_file_label>TO_UPPERCASE_INPUT_FILENAME</options_file_label>
        </input_file>
      </input_files>
      <output_files>
        <output_file>
          <file_type_id>TXT</file_type_id>
          <description>File whose letters have been capitalized</description>
          <options_file_label>TO_UPPERCASE_OUTPUT_FILENAME</options_file_label>
        </output_file>
      </output_files>
    </task>
  </tasks>
</toolkit>
