=== jose-navarro/workflowmaker/data/workflow.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSPY v2004 rel. 2 U (http://www.xmlspy.com) by XMLSPY 2004 Professional Ed. Release 2, Installed Multi for 10 users (SOFTWARE AG) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="workflow">
		<xs:annotation>
			<xs:documentation>Comment describing your root element</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="id" type="xs:token"/>
				<xs:element name="description" type="xs:token"/>
				<xs:element name="toolkit_id" type="xs:token"/>
				<xs:element name="last_repository_id" type="xs:nonNegativeInteger"/>
				<xs:element name="last_task_id" type="xs:nonNegativeInteger"/>
				<xs:element name="repositories" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="repository" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:token"/>
										<xs:element name="numerical_id" type="xs:nonNegativeInteger"/>
										<xs:element name="position">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="x" type="xs:decimal"/>
													<xs:element name="y" type="xs:decimal"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="tasks" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="task" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="id" type="xs:token"/>
										<xs:element name="numerical_id" type="xs:nonNegativeInteger"/>
										<xs:element name="sequential_id" type="xs:nonNegativeInteger"/>
										<xs:element name="position">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="x" type="xs:decimal"/>
													<xs:element name="y" type="xs:decimal"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="connections" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="connection" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="from">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:simpleType>
															<xs:restriction base="xs:token">
																<xs:enumeration value="repository"/>
																<xs:enumeration value="REPOSITORY"/>
																<xs:enumeration value="task"/>
																<xs:enumeration value="TASK"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="numerical_id" type="xs:nonNegativeInteger"/>
													<xs:element name="position" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="to">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="type">
														<xs:simpleType>
															<xs:restriction base="xs:token">
																<xs:enumeration value="repository"/>
																<xs:enumeration value="REPOSITORY"/>
																<xs:enumeration value="task"/>
																<xs:enumeration value="TASK"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="numerical_id" type="xs:nonNegativeInteger"/>
													<xs:element name="position" type="xs:integer"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== jose-navarro/workflowmaker/samples/text_file_processing/sample_workflowmaker_files/text_file_processing_workflow_01.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<workflow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="workflow.xsd">
  <id>TEXT_FILE_HANDLING_WK01</id>
  <description>Text file handling example workflow 01</description>
  <toolkit_id>TEXT_FILE_PROCESSING_TOOLKIT</toolkit_id>
  <last_repository_id>2</last_repository_id>
  <last_task_id>3</last_task_id>
  <repositories>
    <repository>
      <id>REPO_2</id>
      <numerical_id>0</numerical_id>
      <position>
        <x>2798</x>
        <y>2900</y>
      </position>
    </repository>
    <repository>
      <id>REPO_1</id>
      <numerical_id>4</numerical_id>
      <position>
        <x>2794</x>
        <y>2417</y>
      </position>
    </repository>
  </repositories>
  <tasks>
    <task>
      <id>TO_UPPERCASE</id>
      <numerical_id>3</numerical_id>
      <sequential_id>1</sequential_id>
      <position>
        <x>2646</x>
        <y>2572</y>
      </position>
    </task>
    <task>
      <id>REVERSE</id>
      <numerical_id>2</numerical_id>
      <sequential_id>2</sequential_id>
      <position>
        <x>2968</x>
        <y>2571</y>
      </position>
    </task>
    <task>
      <id>INTERLEAVE</id>
      <numerical_id>1</numerical_id>
      <sequential_id>3</sequential_id>
      <position>
        <x>2799</x>
        <y>2745</y>
      </position>
    </task>
  </tasks>
  <connections>
    <connection>
      <from>
        <type>repository</type>
        <numerical_id>4</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>2</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>repository</type>
        <numerical_id>4</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>3</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>1</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>repository</type>
        <numerical_id>0</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>2</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>1</numerical_id>
        <position>1</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>3</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>1</numerical_id>
        <position>0</position>
      </to>
    </connection>
  </connections>
</workflow>

=== jose-navarro/workflowmaker/samples/image_processing/sample_workflowmaker_files/image_processing_workflow.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<workflow xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:noNamespaceSchemaLocation="workflow.xsd">
  <id>IMAGE_PROCESSING_WORKFLOW</id>
  <description>A workflow combining several image processing tools</description>
  <toolkit_id>IMAGE_PROCESSING_TOOLKIT</toolkit_id>
  <last_repository_id>2</last_repository_id>
  <last_task_id>11</last_task_id>
  <repositories>
    <repository>
      <id>REPO_1</id>
      <numerical_id>0</numerical_id>
      <position>
        <x>2952</x>
        <y>2146</y>
      </position>
    </repository>
    <repository>
      <id>REPO_2</id>
      <numerical_id>1</numerical_id>
      <position>
        <x>3145</x>
        <y>3283</y>
      </position>
    </repository>
  </repositories>
  <tasks>
    <task>
      <id>PNG2JPG</id>
      <numerical_id>12</numerical_id>
      <sequential_id>10</sequential_id>
      <position>
        <x>2772</x>
        <y>2226</y>
      </position>
    </task>
    <task>
      <id>BLUR</id>
      <numerical_id>11</numerical_id>
      <sequential_id>1</sequential_id>
      <position>
        <x>2245</x>
        <y>2411</y>
      </position>
    </task>
    <task>
      <id>CHARCOAL</id>
      <numerical_id>10</numerical_id>
      <sequential_id>2</sequential_id>
      <position>
        <x>2450</x>
        <y>2414</y>
      </position>
    </task>
    <task>
      <id>MOSAIC</id>
      <numerical_id>9</numerical_id>
      <sequential_id>4</sequential_id>
      <position>
        <x>2516</x>
        <y>2566</y>
      </position>
    </task>
    <task>
      <id>OILPAINT</id>
      <numerical_id>8</numerical_id>
      <sequential_id>3</sequential_id>
      <position>
        <x>2655</x>
        <y>2413</y>
      </position>
    </task>
    <task>
      <id>MOSAIC</id>
      <numerical_id>7</numerical_id>
      <sequential_id>5</sequential_id>
      <position>
        <x>2740</x>
        <y>2673</y>
      </position>
    </task>
    <task>
      <id>MOSAIC</id>
      <numerical_id>6</numerical_id>
      <sequential_id>6</sequential_id>
      <position>
        <x>2977</x>
        <y>2782</y>
      </position>
    </task>
    <task>
      <id>MIRROR</id>
      <numerical_id>5</numerical_id>
      <sequential_id>7</sequential_id>
      <position>
        <x>2754</x>
        <y>2878</y>
      </position>
    </task>
    <task>
      <id>ROTATE</id>
      <numerical_id>4</numerical_id>
      <sequential_id>8</sequential_id>
      <position>
        <x>2539</x>
        <y>3001</y>
      </position>
    </task>
    <task>
      <id>GRAYSCALE</id>
      <numerical_id>3</numerical_id>
      <sequential_id>9</sequential_id>
      <position>
        <x>2758</x>
        <y>3077</y>
      </position>
    </task>
    <task>
      <id>JPG2PNG</id>
      <numerical_id>2</numerical_id>
      <sequential_id>11</sequential_id>
      <position>
        <x>2972</x>
        <y>3210</y>
      </position>
    </task>
  </tasks>
  <connections>
    <connection>
      <from>
        <type>repository</type>
        <numerical_id>0</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>12</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>2</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>repository</type>
        <numerical_id>1</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>3</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>2</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>4</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>3</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>5</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>4</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>6</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>5</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>7</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>6</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>8</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>7</numerical_id>
        <position>1</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>9</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>7</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>10</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>9</numerical_id>
        <position>1</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>11</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>9</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>12</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>6</numerical_id>
        <position>1</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>12</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>8</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>12</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>10</numerical_id>
        <position>0</position>
      </to>
    </connection>
    <connection>
      <from>
        <type>task</type>
        <numerical_id>12</numerical_id>
        <position>0</position>
      </from>
      <to>
        <type>task</type>
        <numerical_id>11</numerical_id>
        <position>0</position>
      </to>
    </connection>
  </connections>
</workflow>
